### ISSUE TITLE
Prints options and stops

### ISSUE THREAD

**Issue by greermartin** [carj/CSV2DC#1]
Hi James,
I am trying to run this program and it keeps printing the options when I input the parameters. So, rather than creating the XML records, it simply prints the options in the command terminal. When I pass an incorrect parameter, such as the wrong file name for my CSV, I do get the correct error message. But, when the parameters are correct I only get the options.  I've attached a screenshot of the terminal, so you can see what I mean. Any help would be appreciated. Thanks!
Greer
![options](https://user-images.githubusercontent.com/29988035/51860595-ca723d00-22ff-11e9-9e27-ea51efafeeb4.PNG)

**Comment by carj** [comment]
Hi @greermartin 
Make sure the output directory exists 
> mkdir output

Using your command line arguments I get the following: (note the .\ before csv2dc.cmd)

\Code\CSV2DC> .\csv2dc.cmd -i file.txt -o output -c filename -r metadata -p ns -n http://names
pace.com


Created 5 XML files in output
[file.txt](https://github.com/carj/CSV2DC/files/2807083/file.txt)

Can you try and reproduce using my test file (file.txt)?

**Comment by greermartin** [comment]
Thank you, that worked with the text file. When I tried the same argument with CSV i got the option menu again. Can this work with CSV or do you recommend converting to TXT before running? Thanks again.

**Comment by carj** [comment]
I have released a new version which supports duplicate column names.
[v0.4](https://github.com/carj/CSV2DC/releases/latest)

**Comment by greermartin** [comment]
Thank you, this is great!
