### ISSUE TITLE
Can't find class CSV2Metadata

### ISSUE THREAD

**Issue by greermartin** [carj/CSV2DC#2]
Hi James, I've recently re-downloaded the program and I get an error message when I try to run it (after I've entered the arguments). 
"Error: Could not find or load main class CSV2Metadata
Caused by: java.lang.ClassNotFoundException: CSV2Metadata"
Do you know what could be causing this? I haven't changed my PATH variables for Java recently, and a colleague of mine is getting the same error. I'm trying to get my colleagues to use this program for our ingest workflows, so any advice would be appreciated. Thank you! Greer

**Comment by carj** [comment]
Hi  @greermartin
I've just downloaded the latest [release ](https://github.com/carj/CSV2DC/releases/tag/0.5) and it looks fine. The CSV2Metadata.class file is there.
You should be able just to unzip the release into a folder and see something like:

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       18/07/2019     09:48                lib
d-----       05/03/2019     15:59                output
-a----       18/07/2019     09:48           3381 csv2dc.cmd
-a----       18/07/2019     09:48            248 csv2dc.sh
-a----       18/07/2019     09:48          18265 CSV2Metadata.class
-a----       18/07/2019     09:48           3406 csv2preservica.cmd
-a----       18/07/2019     09:48            272 csv2preservica.sh
-a----       18/07/2019     09:49             36 javahome.txt
-a----       18/07/2019     09:48          11558 LICENSE
-a----       18/07/2019     09:48            346 preservica.properties
-a----       18/07/2019     09:48           4845 README.md
-a----       18/07/2019     09:48            137 _config.yml
```

and run it from a windows shell with:

`C:\CSV2DC>  .\csv2dc.cmd`

If your still having issues try deleting the file "javahome.txt".

**Comment by greermartin** [comment]
Thanks, James, this worked!

**Comment by greermartin** [comment]
Thanks, @carj - it worked!
